### ISSUE TITLE
problema en MacBook

### ISSUE THREAD

**Issue by dsimocab** [Argent77/A7-DlcMerger#10]
Tengo problemas para instalar el A7-DlcMerger en un MacBook con Steam instalado, no se en que carpeta he de ejecutar el archivo setup del DlcMerger. Cuando lo intento en el archivo raiz del juego Baldur`s Gate me da el siguiente error:
Last login: Wed Apr 10 00:08:40 on ttys000
/Users/DSIMOCAB/Library/Application\ Support/Steam/steamapps/common/Baldur\'s\ Gate\ Enhanced\ Edition/setup-DlcMerger ; exit;
DSIMOCAB@MacBook-Air-de-ESTHER ~ % /Users/DSIMOCAB/Library/Application\ Support/Steam/steamapps/common/Baldur\'s\ Gate\ Enhanced\ Edition/setup-DlcMerger ; exit;
[/Users/DSIMOCAB/Library/Application Support/Steam/steamapps/common/Baldur's Gate Enhanced Edition/setup-DlcMerger] WeiDU version 24900

Please run this program in your Infinity Engine game directory.

FATAL ERROR: Failure("Not a game directory")

Press ENTER to exit.

Me podría indicar la ruta correcta, gracias.

**Comment by Argent77** [comment]
The DLC Merger should be placed into the same folder where you can find the file `chitin.key`. Then run `setup-DlcMerger.command` to start the interactive mod installation.

An alternative option to install mods on MacOS is subtledoctor's [MacOS WeiDU Launcher](https://github.com/subtledoctor/MacOS_Weidu_Launcher) which also provides a GUI interface.
