### ISSUE TITLE
Merger and Near Infinity

### ISSUE THREAD

**Issue by lambda-dom** [Argent77/A7-DlcMerger#4]
Not sure, I should open an issue with this mod or Near Infinity, but:

Currently, on latest v2.6 and latest releases of Dlc Merger and Near Infinity, using this mod on top of a fresh installation (that is, no other mods), Near Infinity cannot read biff files (virtually everything). I never had this issue as I always used modmerge; reverting to it (that is, uninstall mod, install modmerge), everything is fine again.

On arch linux, using an ext4 case-insensitive partition, with GOG linux version of BG EE and SoD. Any more info needed, just holler.

**Comment by Argent77** [comment]
Does the game work correctly with DLC Merger being installed? Does Near Infinity show any error messages in the debug log (open via menu `Tools > Show Debug Console`). Please post the content if there is any.

This is just a shot in the dark, but could you try out the mod with the previous WeiDU version (v246)? The current version is known to have some compatibility issues. There is a chance that it also affects the DLC Merger. ([Download](https://github.com/WeiDUorg/weidu/releases/tag/v246.00))

I'll try to reproduce it as soon as I have installed a new Linux VM.

**Comment by lambda-dom** [comment]
I have only loaded the start of a (previously) saved game, but everything seems to be working fine with the mod installed. Installing the mod with WeiDU v246 does not make any difference. Attached is the zipped ouput captured on the terminal, which I believe is basically what is seen in the debug console.

A couple more remarks. First, the initial java warning about reflective access also happens with the modmerge and I never noticed it before. Second, if I install EET in BG EE 2, having dlcmerger in the BG EE 1 installed, the latter some how also becomes tainted and Near Infinity barfs on it with the same error.
[near_infinity.log.zip](https://github.com/Argent77/A7-DlcMerger/files/6373249/near_infinity.log.zip)

**Comment by Argent77** [comment]
The warning message about illegal reflective access is harmless and can be safely ignored.

I was able to reproduce this issue. From what I can see this is an issue with Near Infinity. The mod itself works fine.

I have opened a related issue for Near Infinity if you want to report further details: https://github.com/NearInfinityBrowser/NearInfinity/issues/137
