### ISSUE TITLE
Feature Request - Find and Install Everything

### ISSUE THREAD

**Issue by Felipefpl** [Argent77/A7-DlcMerger#7]
It would be nice if dlc-merger had the option to find/install everything or a single mod without having to type its name, just detecting the mods in the same folder as the game (i know this must be complicated so no hurry ;) ). Just a suggestion. :+1: 

Edit - didnt want to create an issue just for this, dlc-merger tried to merge the webcache compressed file from GOG's version, strange since it doesnt have the structure of an weidu's mod.

**Comment by Argent77** [comment]
Could you be more specific? DLC Merger already has an option to automatically merge all available DLC archives found in the game.

The issue with "webcache" already came up some time ago ([link](https://forums.beamdog.com/discussion/comment/1051964/#Comment_1051964)). It will produce some warnings but the actual merge should be skipped. It is not possible to look into zip archives ahead of unpacking with WeiDU (and using external tools for this is quite messy and somewhat error-prone.)

**Comment by Felipefpl** [comment]
> Could you be more specific? DLC Merger already has an option to automatically merge all available DLC archives found in the game.

I should have tested this more carefully. Sorry for that.

> The issue with "webcache" already came up some time ago ([link](https://forums.beamdog.com/discussion/comment/1051964/#Comment_1051964)). It will produce some warnings but the actual merge should be skipped. It is not possible to look into zip archives ahead of unpacking with WeiDU (and using external tools for this is quite messy and somewhat error-prone.)

I see, i just thought it was worth to mention this. It would be nice if dlc-merger didnt report anything about webcache to avoid those dumb questions such as mine in the future. ;) :P

**Comment by Argent77** [comment]
Fixed in [v1.4](https://github.com/Argent77/A7-DlcMerger/releases/tag/v1.4)
