### ISSUE TITLE
Cant use dlc-merger if another mod is uncompressed in the game's folder

### ISSUE THREAD

**Issue by Felipefpl** [Argent77/A7-DlcMerger#8]
This happened while i have dlc-merger and EEUITweaks uncompressed in the baldur's gate folder. Dlc-merger gives me an error msg saying: 

"Windows cant access the device, path or specified file. Perhaps you dont have the proper permissions to access the item.)

After displaying this msg the .exe file of dlc-merger is automatically deleted. This doesnt happen if i remove the EEUITweaks files/folder before using dlc-merger. Also, i didnt install EEUITweaks prior to dlc-merger. I'm using win7 and the 64 bit version of dlc-merger, i attached the debug file to help.
[SETUP-DLCMERGER.zip](https://github.com/Argent77/A7-DlcMerger/files/12536642/SETUP-DLCMERGER.zip)

**Comment by Argent77** [comment]
That sounds more like the work of an antivirus or security tool which performed some thorough scanning or even deleted the file or moved it into quarantine. The WeiDU executable uses (or used) mechanisms that were commonly detected as potentially harmful by some overzealous virus scanners. That it happened in combination with EEUITweaks could just be a coincidence, or maybe the combination of both file versions triggered an alarm somewhere.

**Comment by Felipefpl** [comment]
I see, but i dont have any anti-virus, windows defender is always disabled here.

**Comment by Argent77** [comment]
If you can you reproduce this behavior then it might be a good idea to open a bug report in the WeiDU forums. At that early stage the actual mod content shouldn't be relevant yet.

**Comment by Felipefpl** [comment]
Done - https://forums.pocketplane.net/index.php?board=44.0
