### ISSUE TITLE
Missing executable

### ISSUE THREAD

**Issue by jstripoli** [Argent77/A7-DlcMerger#9]
Readme says to run "setup-DlcMerger.exe" but that file does not exist in the directory.

**Comment by jstripoli** [comment]
I also see this issue has previously been brought up and closed, credited to overzealous anti-virus software. However, the file is not even listed in the gitHub directory.

**Comment by Argent77** [comment]
The executable is not hosted directly in the repository. However they are included in the prepared releases.

You can download prepared packages with the setup executable from the Releases page: https://github.com/Argent77/A7-DlcMerger/releases/latest

The following packages include a setup executable:
- `win-64bit-A7-DlcMerger-<version>.zip` (for 64-bit Windows)
- `win-32bit-A7-DlcMerger-<version>.zip` (for 32-bit Windows)
- `lin-A7-DlcMerger-<version>.zip` (for 64-bit Linux)
- `mac-A7-DlcMerger-<version>.zip` (for macOS)

If you downloaded either of the packages and couldn't find a `setup-DlcMerger` executable then it has been most likely removed by your anti-virus solution.

`A7-DlcMerger-<version>.iemod` is a special package format for the Project Infinity mod manager and does not include a setup binary. The source  code packages also do no include setup binaries.
